### ISSUE TITLE
Running kubelet on docker

### ISSUE THREAD

**Issue by jianzhangbjz** [kiwenlau/single-kubernetes-docker#1]
Hi kiwenlau,

K8s官方release的kubernetes-server-linux-amd64.tar.gz包中唯独没有kubelet的tar包，请问你是如何在容器中运行kubelet的呢？我看官方的推荐方式是apiserver,scheduler,controller-manager,etcd在容器中运行，而kubectl,kubelet,kube-proxy是以二进制的方式直接在节点运行吧

**Comment by kiwenlau** [comment]
kubelet在:

```
kubernetes/server/bin/kubelet 
```

Kubernetes各个组件既可以都运行在容器里，也可以直接运行在本机上

**Comment by jianzhangbjz** [comment]
@kiwenlau 这个是一个二进制文件，你是在容器里直接运行这个二进制文件？比如，在kubernetes/server/bin的目录下的kube-apiserver.tar ，我们可以通过docker load --input kube-apiserver.tar 加载为docker image, 然后通过docker run -d gcr.io/google_containers/kube-apiserver:xxx xxxx 来运行，但是kubelet能通过这种方式运行吗？
